package com.src.main;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.junit4.SpringRunner;

import com.src.main.entities.Aluno;
import com.src.main.repository.AlunoRepository;

@RunWith(SpringRunner.class)
@SpringBootTest
public class FitClubApplicationTests {

//	@Autowired // This means to get the bean called alunoRepository
//	// Which is auto-generated by Spring, we will use it to handle the data
//	private AlunoRepository alunoRepository;
	
	@Test
	public void contextLoads() {
//		Aluno aluno = new Aluno();
//		aluno.setName("Rodrigo");
//		aluno.setCpf("106.030.867-30");
//		aluno.setRg("12947676-8");
//		aluno.setEmail("rodrigo.castro@gmail.com");
//		aluno.setTelefone("(21)96747-3574");
//		
//		alunoRepository.save(aluno);
		
		
	}

}
